ITAM-DS/mate-computacional

- alumnos/FedericoGarza/loquesea.txt
Es una prueba de cómo enviar tareas.
> Prueba Tarea 1

- alumnos/JoseCopca/hola.txt
> Tarea de prueba

- alumnos/mdelatr/prueba.txt
Aqui van comentarios de la tarea
> Sumulación tarea

- alumnos/MauricioTrejo/hola.txt
> hice un mensaje

- alumnos/alonsogv/hola.txt
Intenté hacer esto, pero no salió
> Nueva tarea

- alumnos/antonio1695/primertarea.txt
> Primer tarea

- alumnos/DiegoVillegasA/holamundo.txt
> Primera Tarea

- alumnos/manemarron/hola.txt
> hola mundo manemarron

- alumnos/Shotzo/ProyectoEuler1.ipynb
- alumnos/Shotzo/ProyectoEuler2.ipynb
- alumnos/Shotzo/ProyectoEuler3.ipynb
- alumnos/Shotzo/prueba.txt
- alumnos/Shotzo/prueba2.txt
Tarea del Proyecto Euler para entregar el 3 de febrero del 2015
> Proyecto Euler (1-3)

- alumnos/diegoteran/project_euler/ProjectEuler1.ipynb
- alumnos/diegoteran/project_euler/ProjectEuler2.ipynb
- alumnos/diegoteran/project_euler/ProjectEuler3.ipynb
> Project Euler 1-3

- alumnos/manemarron/project_euler/ProjectEuler1.ipynb
- alumnos/manemarron/project_euler/ProjectEuler2.ipynb
- alumnos/manemarron/project_euler/ProjectEuler3.ipynb
Primeros tres ejercicios del Project Euler
> Project euler

- alumnos/mcarranzba/Proyect_Euler_1_142949.ipynb
Creo que quedaron bien. Saludos.
> Problemas 1, 2 y 3 de Proyect Euler

- alumnos/mcarranzba/Proyect_Euler_6_y_9.ipynb
> Euler 6 y 9

- alumnos/YasminTC/transformaciones.py
> tarea transformaciones

- alumnos/alonsogv/project_euler/project_euler6.ipynb
- alumnos/alonsogv/project_euler/project_euler9.ipynb
- alumnos/alonsogv/transformaciones.py
Ésta es la tarea de la semana pasada. Olvidé hacer el pull request. Aun así no estaba completa...
> Tarea atrasada

- alumnos/YasminTC/Binario_Hexadecimal.ipynb
- alumnos/YasminTC/Binario_a_decimal.ipynb
- alumnos/YasminTC/Clase_2_0-computacion-numerica.ipynb
- alumnos/YasminTC/Decimal_a_binario.ipynb
- alumnos/YasminTC/Untitled0.ipynb
Tarea: Cambios de base
Actividad: computación numerica
> Tarea de cambios de base

- alumnos/manemarron/project_euler/ProjectEuler031.ipynb
En mi anterior pull request aun no incluía la solución al problema 31.
> Project Euler 31

- alumnos/mcarranzba/ProyectE17y31.ipynb
> PE 17 y 31

- alumnos/DiegoVillegasA/examen/Primer_Examen_Parcial.ipynb
Hola profesor,
Tenía idea de cómo resolver la sexta pregunta, pero python me traicionó jeje. Espero no haber escrito mucho babosada en la parte a mano :P 
Saludos!
> Examen Resuelto

- alumnos/alonsogv/CosasParaExamen/SingleDigitAndDoubleDigit.ipynb
- alumnos/alonsogv/examen/examen/Primer Examen Parcial-Copy0.ipynb
- alumnos/alonsogv/examen/examen/Primer Examen Parcial.ipynb
- alumnos/alonsogv/examen/examen/factorial.py
- alumnos/alonsogv/examen/examen/strange_floats_dp.m
- alumnos/alonsogv/examen/examen/strange_floats_sp.m
Me comió la hora. Aun así subo el resto después :(
> Intento de examen

- alumnos/LoreMD/Examen/Primer Examen Parcial Copia.ipynb
- alumnos/LoreMD/Examen/Primer_Examen_Parcial_Copia2.ipynb
- alumnos/LoreMD/Examen/Untitled0.ipynb
- alumnos/LoreMD/Examen/decimalBinarioHexadecimal.py
- alumnos/LoreMD/Examen/factorial.py
- alumnos/LoreMD/Examen/strange_floats_dp.m
- alumnos/LoreMD/Examen/strange_floats_sp.m
perdón por la hora (pero llegue a mi casa mas trade de lo que esperaba)
:)
> EXAMEN parcial 1

- alumnos/antonio1695/Tarea6/Tarea6_Raices.ipynb
Una disculpa por la demora, no lograba hacer el push. Espero aún sea válido.
> Tarea 6, raices.

- alumnos/DiegoVillegasA/Tareas/Tarea_Raices.ipynb
Hola, te mando, algo temprano, los primeros avances de la tarea. Me faltan unos detallitos y ver por qué no me salen más eficientes los últimos algoritmos en comparación de los primeros.
Saludos!
> Primer avance de la Tarea

- alumnos/mcarranzba/Tarea7Abril.ipynb
> Tarea 7 Abril

- alumnos/alonsogv/Proyecto/Modelo del cubo.ipynb
Se agregó la carpeta y un adelanto del trabajo.
> Proyecto Cubo Rubik

- alumnos/mdelatr/proyecto_1.txt
Profesor llevamos tratando de subirlo de mil formas e incluso se lo mandamos por mail, porfín me dejó subirlo :) . Antes solo me dejaba en commit no se porque. Pero de todas formas se encuentra en su mail desde el viernes
> proyecto_1.txt

- alumnos/MauricioTrejo/Presentacion_Proyecto.ipynb
El código de regresión lineal está después de él código de inversionistas :)
> Agregué explicación al código regresión lineal
